baseURL: "https://aravindim.github.io/"
languageCode: "en-us"
title: "Aravind I M"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Aravind I M"
  description: My personal blogging site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/face.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/fav.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Aravind I M" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Aravind I M."
    subtitle: "I build software"
    content: "A passionate software developer. I tend to make use of modern technologies to build apps and websites that looks great, feels fantastic, and functions correctly. I'm also a Linux Enthusiast and have worked as System Administration."
    image: /images/face.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/AravindIM
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/aravind-i-m
        - icon: fab fa-twitter
          url: https://twitter.com/aravind_i_m

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/face.png"
    content: |-
      I am a software developer with a passion for desktop apps, mobile apps, web and cloud computing. I have a background in computer science engineering, and I have a strong interest in the intersection of technology and art. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Rust"
        - "Ruby on Rails"
        - "Flutter"
        - "Python"
        - "Docker"
        - "Linux"
        - "Java"
        - "C/C++"
        - "GTK"
        - "Gitlab CI/CD"
        - "Tensorflow"
        - "Keras"
        - "Android Development"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "TypeScript"
        - "React"
        - "Node"
        - "Express"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Mobile Application Developer"
        company: "Aarista Doorlocks"
        companyUrl: ""
        date: "Aug 2021 - May 2022"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I made Flutter App for controlling the door lock and also for viewing data collected by the doorlock. Initial versions were released in Apache Cordova, later it was switched to Flutter for ease of development and compatibility for both Android and iOS.Used QR code for registering of Doorlocks serial number and had login and registration screen. Connected with Wifi to transmit data to and fro to Firebase."

      - job: "System Administrator"
        company: "SSL Lab - NITC"
        companyUrl: "https://athena.nitc.ac.in"
        date: "Dec 2018 - Feb 2020"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I maintained servers, desktops, websites. During that time, I did the following tasks:
          
          - Handled database updation, system update and software installation.
          - Cluster SSH was used for controlling multiple systems.
          - Created a few scripts to create new users and to update database from CSV files.
          - Setup systems for exams, student registration site on server, backup using borg, DNS updation.
          - Used Xen Orchestra for managing the VMs.
          - Hosted and helped fix issues in the student registration site which was written in PHP
          - Used Reverse Proxy to point to different VMs inside the servers from a single reverse proxy VM.

      - job: "Web Developer"
        company: "FOSSCell - NITC"
        companyUrl: "https://fosscell.org"
        date: "Feb 2020 - Mar 2020"
        featuredLink:
          enable: false
          url: "https://fossmeet.net"
        content: |
          I developed FOSS Meet Website using Express. It used webpacks. It was used for promotion of FOSS Meet 2020.

      - job: "Club Secretary"
        company: "FOSSCell - NITC"
        companyUrl: "https://fosscell.org"
        date: "Aug 2021 - May 2"
        featuredLink:
          enable: false
          url: "https://fosscell.org"
        content: |
          Lead a team of Free Open-source Software Enthusiasts in conducting various Events in my college. Created awareness of FOSS in campus and promoted using it. Conducted workshops and took classes on git and other subjects.

      - job: "Graphic Designer"
        company: "CSEA - NITC"
        companyUrl: "https://assoc.cse.nitc.ac.in/"
        date: "Aug 2019 - Mar 2020"
        content: "Designed Posters and Graphics for Digital Media for Computer Science Engineering Association (CSEA)"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Technology in Computer Science"
        school:
          name: "National Institute of Technology, Calicut"
          url: "https://nitc.ac.in"
        date: "2018 - 2023"
        GPA: "6.38 out of 10"
        content: |-
          My Final Year Project was "Fake Social Media Profile Detection using Deep Learning Techniques"

          Extracurricular Activities
            - Organised Club activities like workshops and talks. Presented in Workshops.
            - Class Representative in the year 2019
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Kendriya Vidhyalaya Puranattukara"
          url: "https://tiruchur.kvs.ac.in/"
        GPA: "8.2 out of 10"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |-
          Computer Science

          Extracurricular Activities
            - Science Exhibition Cluster Level
            - Maths Exhibition School Level

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Lorem Ipsum
        content: Lorem Ipsum
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Compiler for ExPL
        content: Compiler for the language ExPL that compiles for the architecture XSM. This project is maintained as part of Compiler Lab in NITC.
        image: https://opengraph.githubassets.com/hash/AravindIM/compiler
        badges:
          - "Rust"
          - "Compiler"
        links:
          - icon: fab fa-github
            url: https://github.com/AravindIM/compiler

      - title: Load Balancer
        content: A Load Balancer made in Python using libvirt that starts up a new VM and shares the load to it when the CPU threshold is exceeded.
        image: https://opengraph.githubassets.com/hash/AravindIM/cloudy-with-a-chance-of-meatballs
        badges:
          - "Python"
          - "Cloud Computing"
          - "Load Balancer"
        links:
          - icon: fab fa-github
            url: https://github.com/AravindIM/cloudy-with-a-chance-of-meatballs

      - title: NITC Student Hub - Lost and Found
        content: A website for students to post lost and found items
        image: https://opengraph.githubassets.com/hash/dotcomcrashers/nitc-student-hub
        badges:
          - "React"
          - "MySQL"
          - "Express"
          - "Docker"
          - "Docker-compose"
        links:
          - icon: fab fa-github
            url: https://github.com/dotcomcrashers/nitc-student-hub

      - title: Arch Linux Install Script
        content: Fully-automated install script for Arch Linux.
        image: https://opengraph.githubassets.com/hash/AravindIM/arch-install
        badges:
          - "Bash"
          - "Arch Linux"
          - "Linux"
          - "Install"
          - "Config"
          - "Secure Boot"
        links:
          - icon: fab fa-github
            url: https://github.com/AravindIM/arch-install

      - title: FreeTube - Modern UI
        content: Forked version of Freetube with Modern UI
        image: https://opengraph.githubassets.com/hash/AravindIM/FreeTube
        badges:
          - "FreeTube"
          - "FOSS"
          - "UI/UX"
          - "Fork"
        links:
          - icon: fab fa-github
            url: https://github.com/AravindIM/FreeTube
      
      - title: NixOS Flakes Dotfiles
        content: Config files of NixOS with Flakes setup
        image: https://opengraph.githubassets.com/hash/AravindIM/nixos-dotfiles
        badges:
          - "NixOS"
          - "Linux"
          - "Config"
          - "Flakes"
          - "Nix"
        links:
          - icon: fab fa-github
            url: https://github.com/AravindIM/nixos-dotfiles

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: git.aravindim@proton.me
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/AravindIM
      linkedin: https://linkedin.com/aravind-i-m
      twitter: https://twitter.com/aravind_i_m
      instagram: https://instagram.com/aravind.i.m
      facebook: https://facebook.com/aravind-i-m

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Copyleft under AGPL for the page and CC-BY-SA for the content"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
